top = [
		('Jean Shafiroff', 425),
		('Mark Gilbertson', 358),
		('Gillian Miniter', 292),
		('Alexandra Lebenthal', 289),
		('Geoffrey Bradfield', 270),
		('Patrick Mc', 229)
		('Debbie Bancroft', 212),
		('Andrew Saffir', 203),
		('Alina Cho', 193),
		('Somers Farkas', 193),
		('Lydia Fenet', 192),
		('Yaz Herman', 186),
		('Kamie Lightburn', 185),
		('Sharon Bush', 184),
		('Eleanora Kennedy', 173),
		('Allison Aston', 171),
		('Deborah Norville', 168),
		('Mario Buatta', 162),
		('Lucia Hwong Gordon', 161),
		('Muffie Potter Aston', 157),
		('Bonnie Comley', 153),
		('Bettina Zilkha', 152),
		('Jamee Gregory', 149),
		('Amy Fine Collins', 145),
		('Martha Stewart', 134),
		('Stewart Lane', 132),
		('Michael Bloomberg', 131),
		('Audrey Gruss', 130),
		('Rosanna Scotto', 130)
		('Jennifer Creel', 129),
		('Roric Tobin', 127),
		('Daniel Benedict', 126),
		('Donna Karan', 119),
		('Nicole Miller', 117),
		('Dayssi Olarte de Kanavos', 114),
		('Barbara Tober', 113),
		('Tory Burch', 110),
		('Margo Langenberg', 108),
		('Grace Meigher', 104),
		('Karen LeFrak', 103),
		('Fe Fendi', 103),
		('Janna Bullock', 102),
		('Amy Hoadley', 99),
		('Tinsley Mortimer', 97),
		('Fern Mallis', 97),
		('Melissa Berkelhamm', 97),
		('Felicia Taylor', 95),
		('Zani Gugelmann', 94),
		('R. Couri Hay', 94),
		('Liliana Cavendish', 93),
		('Dennis Basso', 92),
		('Audrey Gruss', 92),
		('Michele Gerber Klein', 90),
		('Adelina Wong Ettelson', 90),
		('Liz Peek', 89),
		('Fabiola Beracasa', 88),
		('Barbara Regna', 88),
		('Alexandra Lind Rose', 87),
		('Sylvester Miniter', 87),
		('Olivia Palermo', 87),
		('Russell Simmons', 86),
		('Elizabeth Stribling', 86),
		('Frederick Anderson', 85),
		('Alexandra Seidenfeld', 84),
		('Patricia Shiah', 84),
		('a Kellogg', 83),
		('Lisa Anastos', 83),
		('Karen Klopp', 83),
		('John Demsey', 83),
		('Hilary Geary Ross', 83),
		('Nina Griscom', 81),
		('Douglas Hannant', 81),
		('Diana Taylor', 81),
		('Richard Johnson', 80),
		('Hunt Slonem', 80),
		('Wendy Carduner', 79),
		('Linda Fargo', 79),
		('Claudia Overstrom', 79),
		('Ann Rapp', 79),
		('Anka Palitz', 79),
		('Carol Mack', 78),
		('Kipton Cronkite', 77),
		('Anna Wintour', 77),
		('Alexia Hamm Ryan', 77),
		('Evelyn Lauder', 76),
		('Hamish Bowles', 75),
		('Susan Shin', 74),
		('Maggie Norris', 73),
		('Dawne Marie Grannu', 73),
		('Coco Kopelman', 73),
		('Alec Baldwin', 73),
		('Valesca Guerr', 72),
		('Peter Davis', 72),
		('Olivia Chantecaille', 72),
		('Michele Herbert', 72),
		('Mary Van Pelt', 72),
		('Cynthia Lufkin', 72),
		('Rachel Roy', 72),
		('Paula Zahn', 71),
		('Bette Midler', 71),
		('Margaret Russell', 70)
	]
